title: John Doe # your name (or website title) here
logo: "/images/MyPicture.jpg?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Game developer:
  -Unity C#
  
  Web design:
  -php
  -css
  -mySql
  
  <br><br>
  My email: domacrnko93@gmail.com
  Phone: +385 91 623 0402
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
